[theme]
base="light"
primaryColor="#CD7F32"             # Bronze Orange (buttons/accents)
backgroundColor="#0E4D64"          # Bronze Blue (main background)
secondaryBackgroundColor="#145374" # Lighter bronze blue (sidebar/panels)
textColor="#FFFFFF"                # White text for contrast
font="sans serif"
